"""empty message

Revision ID: e64b8ded4447
Revises: 
Create Date: 2021-04-30 03:01:47.313954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64b8ded4447'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('shop_name', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('imagefile', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('tailor_type', sa.Integer(), nullable=False),
    sa.Column('is_embroidery', sa.Integer(), nullable=True),
    sa.Column('is_partywear', sa.Integer(), nullable=True),
    sa.Column('is_shrugs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('shop_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('view_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('fabric', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('product_image', sa.String(length=20), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_collections')
    op.drop_table('tailor')
    # ### end Alembic commands ###
